### ISSUE TITLE
Needs to be touched up for Firefox 45

### ISSUE THREAD

**Issue by Gitoffthelawn** [einaregilsson/Scroll-Search-Engines#2]
Hi Einar.  You probably know, but reviews indicate that this extension is not working in Firefox 45.  The reviews are still coming in as 5-Stars (even when they report that it is no longer working), so obviously people really appreciate this extension.

**Comment by einaregilsson** [comment]
Have just released version 1.1 which works in FF 45, and no longer requires extra addons to get old-style search functionality backs. The addon now scrolls the engines (obviously), but also adds the engine icons back into the window.

**Comment by Gitoffthelawn** [comment]
Wow!  That's great!  Thanks Einar!
